javascript-functions - Evan Hong
EvanS-Hong/c0123-code-solutions pull request #29
Opened 2023-01-31 19:33 UTC by EvanS-Hong

![image](https://user-images.githubusercontent.com/121647785/215863730-d47200d7-96f3-4985-86b2-d0e9ad27d28c.png)

2023-01-31 19:43 UTC, JenBowman1 requested changes
Hi Eva, this looks good! can you call your functions so I know if they work?

2023-01-31 19:54 UTC, EvanS-Hong commented
![image](https://user-images.githubusercontent.com/121647785/215868109-6da9f4e8-e4ca-417d-8dfe-5bca3ab3db84.png)

2023-01-31 19:59 UTC, shawnkost requested changes
Hey Evan! A couple small changes requested below

2023-01-31 19:59 UTC, shawnkost commented on javascript-functions/main.js
> +  return minutes +' minutes is ' + seconds + ' seconds.' ;
You should only return `seconds` here

2023-01-31 19:59 UTC, shawnkost commented on javascript-functions/main.js
> +  var person = {
Instead of defining the object here, you should be defining it when you call your function, because you're passing the object as a parameter

2023-01-31 19:59 UTC, shawnkost commented on javascript-functions/main.js
> +var getFirstNameResults = getFirstName('person')
Person object just be defined here when you call it

2023-01-31 20:20 UTC, shawnkost requested changes
Still one small change that wasn't fixed from my previous review. You need to update `convertMinutesToSeconds` to only return `seconds`

2023-01-31 21:34 UTC, EvanS-Hong commented
![image](https://user-images.githubusercontent.com/121647785/215888495-b3869870-216c-427e-8e58-65daa029e731.png)

2023-02-01 17:13 UTC, shawnkost approved these changes
👍🏻

2023-02-01 17:32 UTC, merged